"""empty message

Revision ID: 39247da55647
Revises: d1ed8e9922a0
Create Date: 2021-04-09 12:32:06.856526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39247da55647'
down_revision = 'd1ed8e9922a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_forms_types_of_service')
    op.drop_table('organizations_service_forms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations_service_forms',
    sa.Column('id_organization', sa.INTEGER(), nullable=False),
    sa.Column('id_service_form', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_organization'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['id_service_form'], ['service_forms.id'], ),
    sa.PrimaryKeyConstraint('id_organization', 'id_service_form')
    )
    op.create_table('service_forms_types_of_service',
    sa.Column('id_service_form', sa.INTEGER(), nullable=False),
    sa.Column('id_type_of_service', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id_service_form'], ['service_forms.id'], ),
    sa.ForeignKeyConstraint(['id_type_of_service'], ['types_of_service.id'], ),
    sa.PrimaryKeyConstraint('id_service_form', 'id_type_of_service')
    )
    # ### end Alembic commands ###
